import { useEffect, useMemo, useState } from 'react'
import { useNavigate } from 'react-router-dom'
import { History, Search, X } from 'lucide-react'
import { toast } from 'sonner'
import TableSkeleton from '../components/TableSkeleton'
import { Pagination } from '../components/Pagination'
import { listMovementsFiltered, type StockMovementRow } from '../lib/stockApi'
import { listProducts, type ProductRow } from '../lib/productApi'

const PAGE_SIZE = 25

const TYPE_META: Record<string, { label: string; cls: string; sign: string }> = {
  IN:     { label: 'รับเข้า',  cls: 'bg-green-100 text-green-700',  sign: '+' },
  OUT:    { label: 'ตัดออก',   cls: 'bg-red-100 text-red-600',      sign: '−' },
  ADJUST: { label: 'ปรับปรุง', cls: 'bg-blue-100 text-blue-600',    sign: '±' },
}

// Prefixes generated by new StockAdjustmentPage
const STOCK_DOC_PREFIXES = ['GR-', 'GI-', 'ADJ-']

function refIsSalesDoc(ref: string) {
  return ref.length > 0 && !STOCK_DOC_PREFIXES.some(p => ref.startsWith(p))
}

function fmtDate(iso: string) {
  return new Date(iso).toLocaleDateString('th-TH', {
    day: '2-digit', month: 'short', year: '2-digit',
    hour: '2-digit', minute: '2-digit',
  })
}

/** e.g. "billblock.official@gmail.com" → "billblock.official" */
function shortEmail(email: string): string {
  return email.includes('@') ? email.split('@')[0] : email
}

function defaultFrom(): string {
  const d = new Date()
  d.setDate(d.getDate() - 30)
  return d.toISOString().slice(0, 10)
}

function defaultTo(): string {
  return new Date().toISOString().slice(0, 10)
}

// ─── Reference cell ───────────────────────────────────────────────────────────
function RefCell({ ref: refDoc, navigate }: { ref: string; navigate: ReturnType<typeof useNavigate> }) {
  if (!refDoc) {
    return <span className="text-slate-200 text-sm">—</span>
  }

  const isStockDoc  = STOCK_DOC_PREFIXES.some(p => refDoc.startsWith(p))
  const isSalesDoc  = refIsSalesDoc(refDoc)

  // Stock adjustment docs → link to adjustments page (no detail yet, future-proof)
  if (isStockDoc) {
    return (
      <span className="inline-flex items-center gap-1 rounded-md bg-slate-100 px-2 py-0.5 font-mono text-xs font-semibold text-slate-600">
        {refDoc}
      </span>
    )
  }

  // Sales documents (invoice, receipt, etc.) → style as blue link-badge
  if (isSalesDoc) {
    return (
      <button
        onClick={() => navigate('/documents')}
        title={`ค้นหาเอกสาร ${refDoc} ในรายการเอกสาร`}
        className="inline-flex items-center gap-1 rounded-md bg-blue-50 px-2 py-0.5 font-mono text-xs font-semibold text-blue-600 hover:bg-blue-100 transition-colors"
      >
        {refDoc}
      </button>
    )
  }

  // Unknown format — show plain muted
  return <span className="font-mono text-xs text-slate-400">{refDoc}</span>
}

// ─── Main ─────────────────────────────────────────────────────────────────────

export default function StockMovementPage() {
  const navigate = useNavigate()
  const [movements, setMovements] = useState<StockMovementRow[]>([])
  const [products, setProducts] = useState<Map<string, ProductRow>>(new Map())
  const [loading, setLoading] = useState(true)
  const [search, setSearch] = useState('')
  const [filterType, setFilterType] = useState<string>('all')
  const [filterFrom, setFilterFrom] = useState(defaultFrom)
  const [filterTo, setFilterTo] = useState(defaultTo)
  const [page, setPage] = useState(1)

  async function load(from: string, to: string) {
    setLoading(true)
    try {
      const [mvs, prods] = await Promise.all([
        listMovementsFiltered({ from, to }),
        listProducts(),
      ])
      setMovements(mvs)
      setProducts(new Map(prods.map(p => [p.id, p])))
      setPage(1)
    } catch {
      toast.error('โหลดประวัติสต็อกไม่สำเร็จ')
    } finally {
      setLoading(false)
    }
  }

  useEffect(() => {
    void load(filterFrom, filterTo)
  // eslint-disable-next-line react-hooks/exhaustive-deps
  }, [])   // initial load only; date range changes trigger manual re-fetch

  function applyDateFilter() {
    void load(filterFrom, filterTo)
  }

  function clearDateFilter() {
    const from = defaultFrom()
    const to   = defaultTo()
    setFilterFrom(from)
    setFilterTo(to)
    void load(from, to)
  }

  const isCustomRange = filterFrom !== defaultFrom() || filterTo !== defaultTo()

  // ─── Client-side filter (type + search text) ─────────────────────────────
  const filtered = useMemo(() => {
    const q = search.trim().toLowerCase()
    return movements.filter(m => {
      if (filterType !== 'all' && m.movement_type !== filterType) return false
      if (q) {
        const prod    = products.get(m.product_id)
        const name    = prod?.name.toLowerCase() ?? ''
        const sku     = prod?.sku.toLowerCase() ?? ''
        const ref     = m.reference_document.toLowerCase()
        const noteStr = m.note.toLowerCase()
        if (!name.includes(q) && !sku.includes(q) && !ref.includes(q) && !noteStr.includes(q)) return false
      }
      return true
    })
  }, [movements, products, search, filterType])

  const totalPages = Math.ceil(filtered.length / PAGE_SIZE)
  const paginated  = filtered.slice((page - 1) * PAGE_SIZE, page * PAGE_SIZE)

  return (
    <div className="w-full p-6 md:p-8 lg:p-10">

      {/* Header */}
      <div className="mb-6 flex items-center gap-3">
        <div className="flex h-10 w-10 items-center justify-center rounded-xl bg-slate-100">
          <History size={20} className="text-slate-600" />
        </div>
        <div>
          <h1 className="text-2xl font-bold text-slate-800">ประวัติสต็อก</h1>
          <p className="text-sm text-slate-400">
            บันทึกการเคลื่อนไหวทั้งหมด
            {!loading && <span className="ml-1 font-medium text-slate-600">({movements.length} รายการ)</span>}
          </p>
        </div>
      </div>

      {/* ── Filters ── */}
      <div className="mb-4 flex flex-wrap items-end gap-2">

        {/* Search */}
        <div className="relative min-w-48 flex-1">
          <Search size={14} className="absolute left-3 top-1/2 -translate-y-1/2 text-slate-400" />
          <input
            value={search}
            onChange={e => { setSearch(e.target.value); setPage(1) }}
            placeholder="ค้นหาสินค้า / SKU / อ้างอิง / หมายเหตุ"
            className="w-full rounded-lg border border-slate-200 bg-white py-2 pl-8 pr-3 text-sm text-slate-700 outline-none focus:border-slate-400"
          />
        </div>

        {/* Movement type */}
        <select
          value={filterType}
          onChange={e => { setFilterType(e.target.value); setPage(1) }}
          className="rounded-lg border border-slate-200 bg-white px-3 py-2 text-sm text-slate-600 outline-none focus:border-slate-400"
        >
          <option value="all">ทุกประเภท</option>
          <option value="IN">รับเข้า</option>
          <option value="OUT">ตัดออก</option>
          <option value="ADJUST">ปรับปรุง</option>
        </select>

        {/* Date range */}
        <div className="flex items-end gap-1.5">
          <div>
            <p className="mb-1 text-[11px] font-medium text-slate-400">จากวันที่</p>
            <input
              type="date" value={filterFrom}
              onChange={e => setFilterFrom(e.target.value)}
              onBlur={applyDateFilter}
              className="rounded-lg border border-slate-200 bg-white px-3 py-2 text-sm text-slate-700 outline-none focus:border-slate-400"
            />
          </div>
          <span className="mb-2 text-slate-300">—</span>
          <div>
            <p className="mb-1 text-[11px] font-medium text-slate-400">ถึงวันที่</p>
            <input
              type="date" value={filterTo}
              onChange={e => setFilterTo(e.target.value)}
              onBlur={applyDateFilter}
              className="rounded-lg border border-slate-200 bg-white px-3 py-2 text-sm text-slate-700 outline-none focus:border-slate-400"
            />
          </div>
          {isCustomRange && (
            <button
              onClick={clearDateFilter}
              title="รีเซ็ตช่วงวันที่"
              className="mb-0.5 flex h-9 w-9 items-center justify-center rounded-lg border border-slate-200 text-slate-400 hover:border-slate-300 hover:text-slate-600 transition-colors">
              <X size={14} />
            </button>
          )}
        </div>

      </div>

      {/* ── Table ── */}
      <div className="overflow-hidden rounded-xl border border-slate-200 bg-white">
        {loading
          ? <TableSkeleton cols={8} rows={8} />
          : (<>
            <div className="overflow-x-auto">
              <table className="w-full text-sm">
                <thead className="bg-slate-50 text-left text-xs text-slate-500">
                  <tr>
                    <th className="px-4 py-3 font-semibold whitespace-nowrap">วันที่</th>
                    <th className="px-4 py-3 font-semibold">สินค้า</th>
                    <th className="px-4 py-3 font-semibold">ประเภท</th>
                    <th className="px-4 py-3 text-right font-semibold">จำนวน</th>
                    <th className="px-4 py-3 text-right font-semibold whitespace-nowrap">คงเหลือหลัง</th>
                    <th className="px-4 py-3 font-semibold">อ้างอิง</th>
                    <th className="px-4 py-3 font-semibold">หมายเหตุ</th>
                    <th className="px-4 py-3 font-semibold">โดย</th>
                  </tr>
                </thead>
                <tbody>
                  {filtered.length === 0 ? (
                    <tr>
                      <td colSpan={8} className="py-16 text-center">
                        <History size={32} className="mx-auto mb-2 text-slate-200" />
                        <p className="text-sm text-slate-400">
                          {movements.length === 0
                            ? 'ยังไม่มีประวัติสต็อกในช่วงเวลานี้'
                            : 'ไม่พบรายการที่ตรงกับเงื่อนไข'}
                        </p>
                      </td>
                    </tr>
                  ) : paginated.map(m => {
                    const typeMeta = TYPE_META[m.movement_type] ?? TYPE_META['ADJUST']
                    const prod     = products.get(m.product_id)
                    const isOut    = m.movement_type === 'OUT'
                    const displayName = shortEmail(m.created_by)

                    return (
                      <tr key={m.id} className="border-t border-slate-100 transition-colors hover:bg-slate-50">

                        {/* วันที่ */}
                        <td className="px-4 py-3 text-[11px] whitespace-nowrap text-slate-400">
                          {fmtDate(m.created_at)}
                        </td>

                        {/* สินค้า */}
                        <td className="px-4 py-3">
                          {prod
                            ? <>
                                <p className="font-medium text-slate-700">{prod.name}</p>
                                {prod.sku && <p className="text-[11px] text-slate-400">SKU: {prod.sku}</p>}
                              </>
                            : <p className="font-mono text-xs text-slate-300">{m.product_id.slice(0, 8)}…</p>
                          }
                        </td>

                        {/* ประเภท */}
                        <td className="px-4 py-3">
                          <span className={`rounded-full px-2 py-0.5 text-[10px] font-semibold ${typeMeta.cls}`}>
                            {typeMeta.label}
                          </span>
                        </td>

                        {/* จำนวน */}
                        <td className={`px-4 py-3 text-right font-bold ${isOut ? 'text-red-500' : 'text-green-600'}`}>
                          {typeMeta.sign}{m.quantity.toLocaleString('th-TH')}
                        </td>

                        {/* คงเหลือหลัง */}
                        <td className="px-4 py-3 text-right font-medium text-slate-700">
                          {m.balance_after.toLocaleString('th-TH')}
                        </td>

                        {/* อ้างอิง */}
                        <td className="px-4 py-3">
                          <RefCell ref={m.reference_document} navigate={navigate} />
                        </td>

                        {/* หมายเหตุ */}
                        <td className="px-4 py-3 max-w-[180px]">
                          {m.note
                            ? <p className="truncate text-sm text-slate-500" title={m.note}>{m.note}</p>
                            : <span className="text-slate-200 text-sm">—</span>
                          }
                        </td>

                        {/* โดย — ชื่อ + tooltip email */}
                        <td className="px-4 py-3 max-w-[120px]">
                          <span
                            title={m.created_by}
                            className="cursor-default truncate text-xs font-medium text-slate-500 hover:text-slate-700 transition-colors"
                          >
                            {displayName}
                          </span>
                        </td>

                      </tr>
                    )
                  })}
                </tbody>
              </table>
            </div>
            <Pagination
              page={page} totalPages={totalPages}
              total={filtered.length} pageSize={PAGE_SIZE}
              onPage={p => setPage(p)}
            />
          </>)
        }
      </div>
    </div>
  )
}
